export const GET_OWNERS = 'GET_OWNER';
export const GET_NAME_OWNER = 'GET_NAME_OWNER';
export const FILTER_BY_OWNER = 'FILTER_BY_OWNER';
export const GET_PROVIDERS = 'GET_PROVIDERS';
export const GET_NAME_PROVIDER = 'GET_NAME_PROVIDER';
export const ID_PROVIDER = 'ID_PROVIDER';
