export const GET_OWNERS = 'GET_OWNER';
export const GET_NAME_OWNER = 'GET_NAME_OWNER';
export const FILTER_BY_OWNER = 'FILTER_BY_OWNER';
export const GET_PROVIDERS = 'GET_PROVIDERS';
export const GET_NAME_PROVIDER = 'GET_NAME_PROVIDER';
export const GET_SERVICE_PROVIDERS = 'GET_SERVICE_PROVIDERS';
export const FILTER_BY_PROVIDER = 'FILTER_BY_SERVICE_PROVIDER';
export const FILTER_BY_SERVICE_PROVIDER = 'FILTER_BY_SERVICE_PROVIDER';